import java.net.URI

/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * To learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.7/samples
 * This project uses @Incubating APIs which are subject to change.
 */

val buildTask = tasks.create<Exec>("build") {
    commandLine("swift", "build", "-c", "release")
    standardOutput = System.out
    errorOutput = System.out
}
val exportTask = tasks.create<Exec>("export") {
    commandLine("swift", "run", "-c", "release")
    standardOutput = System.out
    errorOutput = System.out
    dependsOn(buildTask)
}
val preview = tasks.create<Exec>("start") {
    val directory = layout.projectDirectory.dir("Build").toString()
    val port = project.properties["port"]?.toString() ?: "8000"
    doFirst {
        java.awt.Desktop.getDesktop().browse(URI("http://localhost:$port"))
    }
    commandLine("python3", "-m", "http.server", "-d", directory, port)
    standardOutput = System.out
    errorOutput = System.out
    dependsOn(exportTask)
}